name: test-coverage

on: push

jobs:
  to-test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: snok/install-poetry@master
      - run: make test-coverage
