name: test-coverage

on: push

jobs:
  to-test:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
      - uses: snok/install-poetry@master
      - run: make install
      - run: make test-coverage
